export { default as Button } from "./Button/Button";
export { default as ArrowButton } from "./ArrowButton/ArrowButton";
export { default as Header } from "./Header/Header";
export { default as Section } from "./Section/Section";
export { default as Loading } from "./Loading/Loading";
export { default as Footer } from "./Footer/Footer";
export { default as SideBarMenu } from "./SideBarMenu/SideBarMenu";
export { default as Workplace } from "./Workplace/Workplace";
export { default as Studies } from "./Studies/Studies";
